name: Update data

on:
  schedule:
    - cron: '0 20 * * 1'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Updates the files
    steps:
      - uses: actions/cheackout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.5.2'
      - run: julia src/make_datasets.jl
      - uses: EndBug/add-and-commit@v7
        with:
          message: 'updated datasets'
